---
title: "Delaware Basin CWSRF Analysis"
author: "Richard Barad"
date: "2024-05-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(readxl)
library(gridExtra)
library(scales)
library(kableExtra)
library(tidycensus)

```

Read data from Excel

```{r read_data}

data <- read_excel('Data/De_river_states.xlsx') %>%
  mutate(total = Nature_Based + Gray)
```

## Plots for American Rivers Report

All Projects Across the state and total funding across all three states.

``` {r fig.width=10, fig.height=5,all_projects}


chart1 <- ggplot(data=data,aes(x=State))+
  geom_bar(stat='count',width=0.65,fill='#82AFD3')+
  geom_text(aes(label=after_stat(count)),stat='count',nudge_y = -10)+
  theme_classic()+
  labs(y='Number of Projects',y='State')+
  theme(panel.grid.major.y = element_line(color = "gray90",linewidth = 0.5),plot.title = element_text(hjust = 0.5))

ggsave('outputs/CWSRF_count.png',units='in',width=5,height=5)

chart2 <- ggplot(data=data,aes(x=State,y=total))+
  geom_col(width=0.65,fill='#008e00')+
  geom_text(aes(label = label_dollar()(after_stat(y))), stat = 'summary', fun = 'sum', size=2.7,nudge_y=-100000000)+
  scale_y_continuous(labels = label_dollar())+
  theme_classic()+
  labs(y='Total Funding For Projects',y='State')+
  theme(panel.grid.major.y = element_line(color = "gray90",linewidth = 0.5),plot.title = element_text(hjust = 0.5))

ggsave('outputs/CWSRF_funding.png',units='in',width=5,height=5)

grid.arrange(chart1,chart2,nrow=1)

```
``` {r table}

# Set Census API key - API KEY STORED IN Renviron
readRenviron("~/.Renviron") 

# Fetch total population by state for the 2020 Census
population_data <- get_decennial(
  geography = "state",
  variables = "P1_001N",
  year = 2020,
  output = "wide"
) %>%
  rename(State = NAME, Total_Population = P1_001N) %>%
  filter(State %in% c('Pennsylvania','Delaware','New Jersey')) %>%
  select(-GEOID)


data %>%
  group_by(State) %>% summarise(funding = sum(total),
                               project_count = n()) %>%
  left_join(.,population_data,by='State') %>%
  mutate(per_capita = funding / Total_Population) %>%
  kbl() %>%
  kable_classic()

```


Number of Nature Based Solutions by State.

```{r nature_based_count, fig.width=10, fig.height=5}

count_nature <- data %>% filter(Nature_Based > 0) %>% group_by(State) %>% tally() %>% rename(nature = n)
count_all <- data %>% group_by(State) %>% tally() %>% rename(total = n)

all_count <- left_join(count_nature,count_all,by='State') %>%
  mutate(percent_nbs = nature / total,
         percent_other = 1 - percent_nbs)


chart3 <- ggplot(data=data %>% filter(Nature_Based > 0),aes(x=State))+
  geom_bar(stat='count',width=0.65,fill='#82AFD3')+
  geom_text(aes(label=after_stat(count)),stat='count',nudge_y = -1)+
  theme_classic()+
  labs(y='Number of Projects',y='State')+
  theme(panel.grid.major.y = element_line(color = "gray90",size = 0.5),plot.title = element_text(hjust = 0.5))

ggsave('outputs/nature_based.png',units='in',width=5,height=5)

chart4 <-ggplot(data=all_count,aes(x=State,y=percent_nbs))+
  geom_bar(stat='identity',width=0.65,fill='#008e00')+
  geom_text(aes(label=paste(as.character(round(percent_nbs * 100,1)),'%',setp='')),stat='identity',nudge_y = -0.01)+
  scale_y_continuous(limits=c(0,0.2),labels = scales::percent)+
  labs(y='Percent of Projects',x='State')+
  theme_classic()+
  theme(panel.grid.major.y = element_line(color = "gray90",linewidth = 0.5),plot.title = element_text(hjust = 0.5))

ggsave('outputs/nature_based_pct.png',units='in',width=5,height=5)

grid.arrange(chart3,chart4,nrow=1)

```

```{r nature_based_funding, fig.width=10, fig.height=5}

money_nature <- data %>% filter(Nature_Based > 0) %>% group_by(State) %>% summarize(nature = sum(Nature_Based))
money_all <- data %>% group_by(State) %>% summarize(total = sum(Current_Agreement_Amount))

money_join <- left_join(money_nature,money_all,by='State') %>%
  mutate(percent_nbs = nature / total,
         percent_other = 1 - percent_nbs)

chart5 <- ggplot(data=data,aes(x=State,y=Nature_Based))+
  geom_col(width=0.65,fill='#82AFD3')+
  geom_text(aes(label = label_dollar()(after_stat(y))), stat = 'summary', fun = 'sum', nudge_y = 5000000)+
  scale_y_continuous(labels = label_dollar())+
  theme_classic()+
  labs(y='Project Funding (USD)',y='State')+
  theme(panel.grid.major.y = element_line(color = "gray90",size = 0.5),plot.title = element_text(hjust = 0.5))

ggsave('outputs/nbs_funding.png',units='in',width=5,height=5)

chart6 <- ggplot(data=money_join,aes(x=State,y=percent_nbs))+
  geom_bar(stat='identity',width=0.65,fill='#008e00')+
  geom_text(aes(label=paste(as.character(round(percent_nbs * 100,1)),'%',setp='')),stat='identity',nudge_y = -0.01)+
  scale_y_continuous(limits=c(0,0.2),labels = scales::percent)+
  labs(y='Percent of Funding',x='State')+
  theme_classic()+
  theme(panel.grid.major.y = element_line(color = "gray90",size = 0.5),plot.title = element_text(hjust = 0.5))

ggsave('outputs/nbs_funding_pct.png',units='in',width=5,height=5)

grid.arrange(chart5,chart6,nrow=1)

```

``` {r nature_based_1}

data %>%
  select(State,State_Tracking_Number, Borrower_Name, Nature_Based, Gray) %>%
  pivot_longer(cols=c(-'State',-'State_Tracking_Number',-'Borrower_Name'),names_to='type',values_to='values') %>%
  ggplot(aes(x=State,y=values,fill=type))+
    geom_bar(width=0.7 ,fun = sum, stat = "summary")+
    geom_text(aes(label = label_dollar()(after_stat(y))), stat = 'summary', fun = 'sum',size=2.8,position = position_stack(vjust=0.8))+
    theme_classic()+
    scale_fill_manual(values=c('#CCCCCC','#008e00'),labels=c('Traditional','Nature Based Solution'),name='Project Type')+
    scale_y_continuous(labels = label_dollar())+
    labs(y='Total Funding (USD)',x='State')

ggsave('outputs/nature_based_totals.png',units='in',width=7,height=5)

money_join %>%
  select(percent_nbs,percent_other,State) %>%
  pivot_longer(cols=-State,names_to='type',values_to='values') %>%
  ggplot(aes(x=State,y=values,fill=type))+
    geom_bar(width=0.7,stat='identity', show.legend = FALSE)+
    theme_classic()+
    scale_fill_manual(values=c('#008e00','#CCCCCC'),labels=c('Nature Based Solution','Traditional'),name='Project Type')+
    scale_y_continuous(labels = scales::percent)+
    geom_text(aes(label = paste(round(values * 100,2),'%'),y=values,x=State),size=3,position = position_stack(vjust=0.5))+
    labs(y='Percent of Funding',x='State')

ggsave('outputs/nature_based_totals_percent.png',units='in',width=5,height=5)


```


``` {r nature_based_2}

totals_nbs_cat <- data %>%
  select(State,State_Tracking_Number, Borrower_Name, Silviculture, Land_Conservation, Hydromodification_Habitat_Resto,Green_Infrastructure) %>%
  pivot_longer(cols=c(-'State',-'State_Tracking_Number',-'Borrower_Name'),names_to='type',values_to='values') %>%
  group_by(State,type) %>% summarise(funding=sum(values)) 

totals_nbs_cat %>%
  filter(funding > 0) %>%
  ggplot(aes(x=State,y=funding,fill=type))+
    geom_col(width=0.7)+
    geom_text(aes(label = label_dollar()(after_stat(y))),size=2.6,position = position_stack(vjust=0.5),color='white')+
    theme_classic()+
    scale_y_continuous(labels = label_dollar())+
    scale_fill_manual(values=c('#008e00','#011F5B','#82AFD3','#990000'),labels=c('Green Infrasturcture','Hydromodification/Habitat Restoration','Land Conservation','Silviculture'),name='Project Type')+
    labs(y='Total Funding (USD)',x='State')

ggsave('outputs/nature_based_type.png',units='in',width=7,height=5)

```

```{r de_basin1}

de_river_data <- data %>%
  filter(Basin == 'Yes')

ggplot(data=de_river_data,aes(x=State))+
  geom_bar(stat = "count",width=0.65,fill='#82AFD3')+
  geom_text(aes(label=after_stat(count)),stat='count',nudge_y = -5)+
  theme_classic()+
  labs(y='Number of Projects',x='State')+
  theme(panel.grid.major.y = element_line(color = "gray90",linewidth = 0.5))

ggsave('outputs/DE_Basin_projects_count.png',units='in',width=5,height=5)

ggplot(data=de_river_data,aes(x=State,y=total))+
  geom_col(width=0.65,fill='#008e00')+
  geom_text(aes(label = label_dollar()(after_stat(y))), stat = 'summary', fun = 'sum', size=2.7,nudge_y=-10000000)+
  scale_y_continuous(labels = label_dollar())+
  theme_classic()+
  labs(y='Total Funding (USD)',x='State')+
  theme(panel.grid.major.y = element_line(color = "gray90",linewidth = 0.5))+
  ggtitle('Total Funding for CWSRF Projects By State')

ggsave('outputs/DE_Basin_projects_funding.png',units='in',width=5,height=5)

```

```{r de_basin2}

ggplot(data=de_river_data %>% filter(Nature_Based > 0),aes(x=State))+
  geom_bar(stat = "count",width=0.65,fill='#82AFD3')+
  geom_text(aes(label=after_stat(count)),stat='count',nudge_y = -0.5)+
  theme_classic()+
  labs(y='Number of Projects',x='State')+
  theme(panel.grid.major.y = element_line(color = "gray90",linewidth = 0.5))

ggsave('outputs/DE_Basin_NBS_projects_count.png',units='in',width=5,height=5)

ggplot(data=de_river_data %>% filter(Nature_Based > 0),aes(x=State,y=total))+
  geom_col(width=0.65,fill='#008e00')+
  geom_text(aes(label = label_dollar()(after_stat(y))), stat = 'summary', fun = 'sum', size=2.7,nudge_y=-1000000)+
  scale_y_continuous(labels = label_dollar())+
  theme_classic()+
  labs(y='Total Funding (USD)',x='State')+
  theme(panel.grid.major.y = element_line(color = "gray90",linewidth = 0.5))

ggsave('outputs/DE_Basin_NBS_projects_funding.png',units='in',width=5,height=5)


```

``` {r de_basin_nbs1}

nbs_basin_count <- de_river_data %>% filter(Nature_Based > 0) %>% group_by(State) %>% tally() %>% rename(nbs_count = n)
all_basin_count <- de_river_data %>% group_by(State) %>% tally() %>% rename(all_count = n)

basin_count <- left_join(nbs_basin_count,all_basin_count,by='State') %>%
  mutate(percent_nbs = nbs_count / all_count)

ggplot(data=basin_count,aes(x=State,y=percent_nbs))+
  geom_bar(stat='identity',width=0.65,fill='#008e00')+
  geom_text(aes(label=paste(as.character(round(percent_nbs * 100,1)),'%',setp='')),stat='identity',nudge_y = -0.01)+
  scale_y_continuous(limits=c(0,0.3),labels = scales::percent)+
  labs(y='Percent of Projects',x='State')+
  theme_classic()+
  theme(panel.grid.major.y = element_line(color = "gray90",linewidth = 0.5))

ggsave('outputs/DE_Basin_NBS_projects_pct.png',units='in',width=5,height=5)

```

``` {r de_basin_nbs2}

de_river_data %>%
  select(State,State_Tracking_Number, Borrower_Name, Nature_Based, Gray) %>%
  pivot_longer(cols=c(-'State',-'State_Tracking_Number',-'Borrower_Name'),names_to='type',values_to='values') %>%
  ggplot(aes(x=State,y=values,fill=type))+
    geom_bar(width=0.7 ,fun = sum, stat = "summary")+
    geom_text(aes(label = label_dollar()(after_stat(y))), stat = 'summary', fun = 'sum',size=2.8,position = position_stack(vjust=0.75))+
    theme_classic()+
    scale_fill_manual(values=c('#CCCCCC','#008e00'),labels=c('Traditional','Nature Based Solution'),name='Project Type')+
    scale_y_continuous(labels = label_dollar())+
    labs(y='Total Funding (USD)',x='State')

ggsave('outputs/nature_based_totals_basin.png',units='in',width=7,height=5)

money_nature_basin <- de_river_data %>% filter(Nature_Based > 0) %>% group_by(State) %>% summarize(nature = sum(Nature_Based))
money_all_basin <- de_river_data %>% group_by(State) %>% summarize(total = sum(Current_Agreement_Amount))

money_join_basin <- left_join(money_nature_basin,money_all_basin,by='State') %>%
  mutate(percent_nbs = nature / total,
         percent_other = 1 - percent_nbs)

money_join_basin %>%
  select(percent_nbs,percent_other,State) %>%
  pivot_longer(cols=-State,names_to='type',values_to='values') %>%
  ggplot(aes(x=State,y=values,fill=type))+
    geom_bar(width=0.7,stat='identity', show.legend = FALSE)+
    theme_classic()+
    scale_fill_manual(values=c('#008e00','#CCCCCC'),labels=c('Nature Based Solution','Traditional'),name='Project Type')+
    scale_y_continuous(labels = scales::percent)+
    geom_text(aes(label = paste(round(values * 100,2),'%'),y=values,x=State),size=3,position = position_stack(vjust=0.5))+
    labs(y='Percent of Funding',x='State')

ggsave('outputs/nature_based_totals_basin_percent.png',units='in',width=5,height=5)


```

# Additional PA Focused Analysis for WaterNow

``` {r pa_data}

pa_data <- data %>%
  filter(State == 'Pennsylvania')

```

``` {r disadvanated_communites}

agg <- pa_data %>%
  group_by(Hardship_Disadvantaged_Communit) %>%
  summarize(count = n(),subsidy = sum(Additional_Subsidy_Amount),total = sum(Current_Agreement_Amount)) %>%
  mutate(percent = count / sum(count) * 100,
         percent_total_subsidy = subsidy/sum(subsidy) * 100,
         percent_funding_subsidized = subsidy / total * 100,
         percent_funding = total / sum(total) * 100)


ggplot(agg, aes(x="", y=percent, fill=Hardship_Disadvantaged_Communit))+
  geom_bar(stat="identity", width=2, color="gray80") +
  coord_polar("y", start=0) +
  geom_text(aes(label = paste0(round(percent), "%")),position = position_stack(vjust = 0.5))+
  scale_fill_manual(values=c('#ffe093','lightgreen'),name='Disadvantaged Community')+
  theme_void()+
  labs(title='% of Projects in Pennsylvania Located \n in Disadvantaged Communities, July 2017 to June 2023')

ggsave('outputs/disadvantaged_pie.png',units='in',width=5,height=4)

ggplot(agg, aes(x="", y=percent_funding , fill=Hardship_Disadvantaged_Communit))+
  geom_bar(stat="identity", width=2, color="gray80") +
  coord_polar("y", start=0) +
  geom_text(aes(label = paste0(round(percent_funding), "%")),position = position_stack(vjust = 0.5))+
  scale_fill_manual(values=c('#ffe093','lightgreen'),name='Disadvantaged Community')+
  theme_void()+
  labs(title='% of CWSRF Funding in Pennsylvania Going to Disadvantaged Communities')

ggsave('outputs/percent_pie.png',units='in',width=5,height=4)

hardship_funding <- pa_data %>%
  summarise(subsidy = sum(Additional_Subsidy_Amount),total = sum(Current_Agreement_Amount)) %>%
  mutate(non_subsidy = total - subsidy) %>%
  pivot_longer(cols = everything()) %>%
  filter(name != 'total') %>%
  mutate(percent = value / sum(value) * 100)

ggplot(hardship_funding, aes(x="", y=percent, fill=name))+
  geom_bar(stat="identity", width=2, color="gray80") +
  coord_polar("y", start=0) +
  geom_text(aes(label = paste0(round(percent), "%")),position = position_stack(vjust = 0.5))+
  scale_fill_manual(values=c('#ffe093','lightgreen'),name='',labels=c('Not Subsidized','Subsidized'))+
  theme_void()+
  labs(title='% of CWSRF Funding in Pennslyvania that was Subsized \n July 2017 to June 2023')

ggsave('outputs/percent_subsized_pie.png',units='in',width=5,height=4)

```

``` {r types}

hardship_funding_type <- pa_data %>%
  filter(Hardship_Disadvantaged_Communit == 'Yes') %>%
  mutate(wastewater = Secondary_Treatment + Advanced_Treatment + Infiltration_Inflow_Correction + Sewer_System_Rehabilitation + New_Collector_Sewers + New_Interceptors + CSO_Correction,
         stormwater = Green_Infrastructure + Gray_Infrastructure,
         energy = Renewable_Energy + Energy_Efficiency,
         water_conservation = Water_Efficiency,
         non_point_source = Agricultural_BMPs + Silviculture + Ground_Water__Unknown_Source_ + Brownfields + Sanitary_Landfills + Hydromodification_Habitat_Resto + Individual_Decentralized_Sewage + Land_Conservation) %>%
  select(id,wastewater,stormwater,energy,water_conservation,non_point_source) %>%
  pivot_longer(cols=-id,names_to='Category',values_to='Value') %>%
  filter(Value != 0)

summary_type_hardship <- hardship_funding_type %>% 
  group_by(Category) %>% summarize(funding = sum(Value)) %>%
  mutate(percent = funding / sum(funding))

funding_type <- pa_data %>%
  mutate(wastewater = Secondary_Treatment + Advanced_Treatment + Infiltration_Inflow_Correction + Sewer_System_Rehabilitation + New_Collector_Sewers + New_Interceptors + CSO_Correction,
         stormwater = Green_Infrastructure + Gray_Infrastructure,
         energy = Renewable_Energy + Energy_Efficiency,
         water_conservation = Water_Efficiency,
         non_point_source = Agricultural_BMPs + Silviculture + Ground_Water__Unknown_Source_ + Brownfields + Sanitary_Landfills + Hydromodification_Habitat_Resto + Individual_Decentralized_Sewage + Land_Conservation) %>%
  select(id,wastewater,stormwater,energy,water_conservation,non_point_source) %>%
  pivot_longer(cols=-id,names_to='Category',values_to='Value') %>%
  filter(Value != 0)

summary_type <- funding_type %>% 
  group_by(Category) %>% summarize(funding = sum(Value)) %>%
  mutate(percent = funding / sum(funding))


ggplot()+
  geom_col(data=hardship_funding_type,aes(x='',y=Value,fill=Category))+
  coord_polar("y", start=0) +
  scale_fill_manual(values=c('#fcd253','#7fffb4','#96beff'),labels=c('Non Point Source','Stormwater','Wastewater'),name='Project Category')+
  labs(title='Funding by Project Category in Disadvantaged Communities \n July 2017 to June 2023')+
  theme_void()

ggsave('outputs/type.png',units='in',width=5,height=4)
  

```