---
title: "equity_analysis"
author: "Richard Barad"
date: "2024-06-10"
output: html_document
---

```{r setup, include=FALSE}

library(tidyverse)
library(sf)
library(tidycensus)
library(readxl)
library(tigris)
library(httr)
library(kableExtra)
library(viridis)
library(scales)

```

## Read Project Data

```{r read_data}

data <- read_excel('Data/De_river_states.xlsx') %>%
  mutate(total = Nature_Based + Gray,
         stormwater = Green_Infrastructure + Gray_Infrastructure,
         wastewater = Advanced_Treatment + CSO_Correction + Infiltration_Inflow_Correction + New_Collector_Sewers + New_Interceptors + Secondary_Treatment + Sewer_System_Rehabilitation + Planning_and_Assessments,
         energy_conservation = Energy_Efficiency + Renewable_Energy,
         water_conservation = Water_Efficiency,
         equity_analysis_funding = stormwater + wastewater + energy_conservation + water_conservation) %>%
  st_as_sf(., coords = c("Longitude","Latitude"),crs='EPSG:4326') %>%
  st_transform('EPSG:2272')

```

## Get Urban Areas and map

```{r urban_areas, echo=FALSE}

de_basin <- st_read('Data/DE_Basin.shp') %>% st_transform('EPSG:2272')

#Get Urban Areas and intersect with States

urban_areas <- tigris::urban_areas(year=2020)

states <- tigris::states() %>%
  dplyr::filter(NAME %in% c('Pennsylvania','New Jersey','Delaware'))

states_2272 <- states %>% st_transform('EPSG:2272')

urban_areas <- st_intersection(states,urban_areas) %>% st_transform('EPSG:2272')

#Map quick map

bbox <- st_bbox(de_basin)

xmin <- bbox[1]
ymin <- bbox[2]
xmax <- bbox[3]
ymax <- bbox[4]

ggplot()+
  geom_sf(data=urban_areas,fill='orange',color='transparent')+
  geom_sf(data=states_2272,color='gray40',fill='transparent')+
  geom_sf(data=de_basin,color='lightblue',fill='transparent',linewidth=1)+
  xlim(xmin,xmax)+
  ylim(ymin,ymax)+
  theme_void()

ggsave('urban_areas2.png',height=3.8,width=2)

```
# Get County Boundaries and Determine Counties in Study Area

``` {r counties}

counties <- rbind(counties(state='PA'),counties(state='DE'),counties(state='NJ')) %>% st_transform('EPSG:2272')

# Include counties that have a more 40% overlap with the Basin

basin_counties <- counties %>%
  mutate(area = st_area(.)) %>%
  st_intersection(.,de_basin) %>%
  mutate(basin_area = st_area(.),
         percent_basin = as.numeric(basin_area) / as.numeric(area)) %>%
  filter(percent_basin > 0.4) %>%
  st_drop_geometry() %>%
  select('GEOID','STATEFP','COUNTYFP','NAME') %>%
  inner_join(counties %>% select('geometry','GEOID'),.,by='GEOID')

ggplot()+
  geom_sf(data=states,color='gray50',size=2,fill='transparent')+
  geom_sf(data=basin_counties,fill='#ff9b9b',color='gray60')+
  geom_sf(data=states,fill='transparent')+
  theme_void()

ggsave('study_area.png')

```


# Get Population Data

```{r get_population}

# Get Population Data
pop_PA <- get_decennial('block group',sumfile='dhc',year=2020,state='PA',variable='P1_001N',geometry=TRUE) %>% mutate(state = 'PA')
pop_DE <- get_decennial('block group',sumfile='dhc',year=2020,state='DE',variable='P1_001N',geometry=TRUE) %>% mutate(state = 'DE')
pop_NJ <- get_decennial('block group',sumfile='dhc',year=2020,state='NJ',variable='P1_001N',geometry=TRUE) %>% mutate(state = 'NJ')

pop <- rbind(pop_PA,pop_DE,pop_NJ) %>% st_transform('EPSG:2272')

#Get just census blocks located in study area

basin_blocks <- pop %>% select(-NAME) %>%
  st_centroid() %>%
  st_join(.,basin_counties %>% select(-GEOID),left=FALSE) 

#Determine which census blocks are urban and which are rural - use centroid of census block group

urban_blocks <- basin_blocks[st_intersects(basin_blocks,urban_areas) %>% lengths > 0, ] %>% mutate(urban = 'Urban')
rural_blocks <- basin_blocks[st_intersects(basin_blocks,urban_areas) %>% lengths == 0, ] %>% mutate(urban = 'Rural')

pop_data_basin <- rbind(urban_blocks,rural_blocks) %>%
  st_drop_geometry() %>%
  left_join(.,pop %>% select('GEOID','geometry'),by='GEOID') %>%
  st_as_sf()
```

# Get CJEST DAta

``` {r CJEST}

CEJST_burdened <- st_read('Data/CEJST/usa.shp') %>%
  filter(SF %in% c('New Jersey','Delaware','Pennsylvania')) %>%
  st_transform('EPSG:2272') %>%
  filter(SN_C == 1)

pop_centroid <- pop_data_basin %>% st_centroid()

#Determine which census blocks are overburdened

burdened_blocks <- pop_centroid[st_intersects(pop_centroid,CEJST_burdened) %>% lengths > 0, ] %>% mutate(overburdened = 'Yes')
nonburdned_blocks <- pop_centroid[st_intersects(pop_centroid,CEJST_burdened) %>% lengths == 0, ] %>% mutate(overburdened = 'No')

pop_data_basin <- rbind(burdened_blocks,nonburdned_blocks) %>%
  st_drop_geometry() %>%
  left_join(.,pop_data_basin %>% select('GEOID','geometry'),by='GEOID') %>%
  st_as_sf() %>%
  mutate(area_ft = as.numeric(st_area(.)))

```

# Map Rural / Urban Areas

```{r}
bbox <- st_bbox(pop_data_basin)

xmin <- bbox[1]
ymin <- bbox[2]
xmax <- bbox[3]
ymax <- bbox[4]

ggplot()+
  geom_sf(data=states_2272,fill='gray90')+
  geom_sf(data=pop_data_basin,aes(fill=as.factor(urban)),color='transparent')+
  scale_fill_manual(values=c('lightgreen','pink'),labels=c('Rural','Urban'),name='')+
  geom_sf(data=basin_counties,color='gray60',fill='transparent',size=0.5)+
  geom_sf(data=states_2272,color='gray40',fill='transparent')+
  geom_sf_text(data=basin_counties,aes(label=NAME),size=2.5)+
  xlim(xmin,xmax)+
  ylim(ymin,ymax)+
  theme_void()

ggsave('urban_areas.png',width=3,height=5)

```

``` {r join_project_funding}

#Determine Total CWSRF Funding By County

funding_county <- st_join(data,basin_counties,left=FALSE) %>%
  filter(score > 95) %>%
  group_by(NAME) %>% summarise(funding = sum(equity_analysis_funding)) %>%
  st_drop_geometry()

Data_County1 <- left_join(basin_counties,funding_county,by='NAME') %>%
  st_as_sf() %>%
  select(NAME,GEOID,funding) %>%
  mutate(funding = ifelse(is.na(funding),0,funding))

```

``` {r join_urban_pop}

#Determine Rural / Urban Population by County

pop_county <- pop_data_basin %>%
  mutate(NAME=ifelse(GEOID=='421039501041','Pike',NAME)) %>%
  group_by(NAME,urban,state) %>% summarize(pop = sum(value),area=sum(area_ft)) %>%
  st_drop_geometry() %>%
  pivot_wider(id_cols=c(NAME,state),names_from=urban,values_from=c(pop,area)) %>%
  mutate(pop_Rural = ifelse(is.na(pop_Rural),0,pop_Rural),
         area_Rural = ifelse(is.na(area_Rural),0,area_Rural),
         percent_urban_pop = round(pop_Urban / (pop_Urban + pop_Rural),4),
         percent_urban_area = round(area_Urban / (area_Urban + area_Rural),4)) %>%
  select(NAME,state,pop_Urban,pop_Rural,percent_urban_pop,percent_urban_area)
  
Data_County2 <- left_join(Data_County1,pop_county,by='NAME') %>%
  mutate(funding_per_urban_capita = funding / pop_Urban)

```

```{r join_overburdned}

overburdened <- pop_data_basin %>% filter(urban == 'Urban') %>%
  group_by(NAME,overburdened) %>% summarize(pop = sum(value)) %>%
  st_drop_geometry() %>%
  pivot_wider(id_cols=NAME,names_from=overburdened,values_from=pop) %>%
  mutate(percent_urban_overbudened = Yes / (Yes + No) * 100) %>%
  select(NAME,percent_urban_overbudened)


Data_County3 <- left_join(Data_County2,overburdened,by='NAME')

```


``` {r make_maps}

ggplot()+
  geom_sf(data=states_2272,size=2,fill='gray95')+
  geom_sf(data=Data_County3,aes(fill=funding),color='gray80')+
  scale_fill_distiller(palette='Greens',direction=1,labels = dollar, name='Financing ($)')+
  geom_sf(data=states_2272,fill='transparent',color='gray30')+
  geom_sf_text(data=basin_counties,aes(label=NAME),size=2,color='black')+
  xlim(xmin,xmax)+
  ylim(ymin,ymax)+
  theme_void()

ggsave('financing.png')

ggplot()+
  geom_sf(data=states_2272,size=2,fill='gray95')+
  geom_sf(data=Data_County3,aes(fill=funding_per_urban_capita),color='gray80')+
  scale_fill_distiller(palette='Greens',direction=1,labels = dollar, name='Financing ($) Per \n Urban Capita')+
  geom_sf(data=states_2272,fill='transparent',color='gray30')+
  geom_sf_text(data=basin_counties,aes(label=NAME),size=2,color='black')+
  xlim(xmin,xmax)+
  ylim(ymin,ymax)+
  theme_void()+
  theme(legend.position="bottom",legend.text=element_text(size=7))

ggsave('financing_per_capita.png')

ggplot()+
  geom_sf(data=states_2272,size=2,fill='gray95')+
  geom_sf(data=Data_County3,aes(fill=pop_Urban / 1000),color='gray80')+
  scale_fill_viridis(option='rocket',direction=-1,name='Urban Population \n (thousands)')+
  geom_sf(data=states_2272,fill='transparent',color='gray30')+
  geom_sf_text(data=basin_counties,aes(label=NAME),size=2,color='black')+
  xlim(xmin,xmax)+
  ylim(ymin,ymax)+
  theme_void()+
  theme(legend.position="bottom",legend.text=element_text(size=9))

ggsave('urban_pop.png')

ggplot()+
  geom_sf(data=states_2272,size=2,fill='gray95')+
  geom_sf(data=Data_County3,aes(fill=percent_urban_pop * 100),color='gray80')+
  scale_fill_viridis(option='rocket',direction=-1,name='Percent Urban')+
  geom_sf(data=states_2272 %>% st_transform('EPSG:3857'),fill='transparent',color='gray30')+
  geom_sf_text(data=basin_counties,aes(label=NAME),size=2,color='white')+
  xlim(xmin,xmax)+
  ylim(ymin,ymax)+
  theme_void()+
  theme(legend.position="bottom",legend.text=element_text(size=9))


ggsave('urban_percent.png')

ggplot()+
  geom_sf(data=states_2272,size=2,fill='gray95')+
  geom_sf(data=Data_County3,aes(fill=percent_urban_overbudened),color='gray80')+
  scale_fill_distiller(palette='BuPu',direction=1,name='% of Urban Pop.')+
  geom_sf(data=states_2272,fill='transparent',color='gray30')+
  geom_sf_text(data=basin_counties,aes(label=NAME),size=2,color='black')+
  xlim(xmin,xmax)+
  ylim(ymin,ymax)+
  theme_void()+
  theme(legend.position="bottom",legend.text=element_text(size=9))

ggsave('overburdened_percent.png')

```

``` {r export_results}

Data_county3_org <- Data_County3 %>%
  select(NAME,state,funding,pop_Urban,funding_per_urban_capita,percent_urban_pop,percent_urban_area,percent_urban_overbudened) %>%
  st_drop_geometry()

write.csv(Data_county3_org %>% st_drop_geometry(),'results.csv')
  
```

``` {r map}

ggplot()+
  geom_sf(data=states_2272,size=2,fill='gray95')+
  geom_sf(data=basin_counties,fill='white')+
  geom_sf(data=pop_data_basin %>% filter(overburdened == 'Yes'),aes(fill='#66c2a5'),color='transparent')+
  geom_sf(data=pop_data_basin %>% filter(overburdened == 'Yes' & urban == 'Urban'),aes(fill='#fff39b'),color='transparent')+
  geom_sf(data=pop_data_basin %>% filter(overburdened == 'No' & urban == 'Urban'),aes(fill='#fc8d62'),color='transparent')+
  geom_sf(data=basin_counties,color='gray80',fill='transparent')+
  geom_sf(data=states_2272,fill='transparent',color='gray60')+
  geom_sf_text(data=basin_counties,aes(label=NAME),size=2,color='black')+
  scale_fill_manual(values=c('#66c2a5','#fff39b','#fc8d62'),label=c('CEJST Rural','Non CEJST Urban','CEJST Urban'),name='')+
  xlim(xmin,xmax)+
  ylim(ymin,ymax)+
  theme_void()

ggsave('overburdened_communities.png')

```


``` {r maps}

ggplot()+
  geom_sf(data=data_county3,aes(fill=funding_per_urban_capita))+
  geom_sf(data=urban_basin,fill='orange',color='transparent')+
  scale_fill_viridis()+
  geom_sf(data=de_basin,color='lightblue',fill='transparent',linewidth=1)+
  xlim(xmin,xmax)+
  ylim(ymin,ymax)+
  theme_void()

```